import ledImg from "./assets/products/luces.jpeg";

export const products = [
  {
    id: 1,
    name: "Serie LED blanca cálida 100 focos 5m",
    price: 199,
    features: [
      "5 metros",
      "100 focos LED",
      "Luz blanca cálida",
      "Para exteriores e interiores",
      "Impermeable IP44",
    ],
    img: [ledImg, ledImg, ledImg],
    shein: "https://shein.com",
    mercado: "https://mercadolibre.com",
  },
  {
    id: 2,
    name: "Serie LED multicolor 200 focos 10m",
    price: 349,
    features: [
      "10 metros",
      "200 focos multicolor",
      "8 modos de iluminación",
      "Control remoto",
      "Para exteriores",
      "Impermeable IP65",
    ],
    img: [ledImg, ledImg, ledImg],
    shein: "https://shein.com",
    mercado: "https://mercadolibre.com",
  },
  {
    id: 3,
    name: "Cortina LED 3x2m 300 focos",
    price: 429,
    features: [
      "3x2 metros",
      "300 focos LED",
      "Efecto cascada",
      "Blanco frío",
      "Ideal para fiestas",
      "8 funciones",
    ],
    img: [ledImg, ledImg, ledImg],
    shein: "https://shein.com",
    mercado: "https://mercadolibre.com",
  },
  {
    id: 4,
    name: "Serie LED RGB inteligente 5m",
    price: 289,
    features: [
      "5 metros",
      "Control WiFi",
      "Millones de colores",
      "Compatible con Alexa",
      "Música reactiva",
      "App móvil",
    ],
    img: [ledImg, ledImg, ledImg],
    shein: "https://shein.com",
    mercado: "https://mercadolibre.com",
  },
  {
    id: 5,
    name: "Mini Serie LED 50 focos 2.5m",
    price: 99,
    features: [
      "2.5 metros",
      "50 focos micro LED",
      "Funciona con pilas",
      "Luz blanca cálida",
      "Ideal decoración interior",
    ],
    img: [ledImg, ledImg, ledImg],
    shein: "https://shein.com",
    mercado: "https://mercadolibre.com",
  },
  {
    id: 6,
    name: "Serie LED solar 100 focos 12m",
    price: 259,
    features: [
      "12 metros",
      "Energía solar",
      "100 focos LED",
      "8 horas de duración",
      "Sensor automático",
      "Ahorro energético",
    ],
    img: [ledImg, ledImg, ledImg],
    shein: "https://shein.com",
    mercado: "https://mercadolibre.com",
  },
  {
    id: 7,
    name: "Red LED 2x2m 144 focos",
    price: 189,
    features: [
      "2x2 metros",
      "144 focos LED",
      "Forma de red",
      "Blanco cálido",
      "Fácil instalación",
      "Para decoración",
    ],
    img: [ledImg, ledImg, ledImg],
    shein: "https://shein.com",
    mercado: "https://mercadolibre.com",
  },
  {
    id: 8,
    name: "Serie LED profesional 500 focos 25m",
    price: 699,
    features: [
      "25 metros",
      "500 focos LED",
      "Uso comercial",
      "Multicolor programable",
      "Resistente al clima",
      "Garantía 2 años",
    ],
    img: [ledImg, ledImg, ledImg],
    shein: "https://shein.com",
    mercado: "https://mercadolibre.com",
  },
];
